desc dept;
desc emp;

select * from emp;
select * from dept;

/*
	Query 1
*/
SELECT E.ENAME, E.JOB, E.SAL FROM EMP AS E
JOIN DEPT AS D ON E.DEPTNO = D.DEPTNO
WHERE D.LOC = (SELECT LOC FROM DEPT WHERE LOC LIKE 'CHICAGO');

/*
	Query 2
*/
SELECT EMPNO, ENAME, JOB, DEPTNO FROM EMP
WHERE EMPNO NOT IN (SELECT MGR FROM EMP WHERE NOT ISNULL(MGR)); 

/*
	Query 3
*/
SELECT ENAME, JOB, MGR FROM EMP
WHERE MGR = (SELECT MGR FROM EMP WHERE ENAME LIKE 'BLAKE');

/*
	Query 4
*/
SELECT * FROM EMP
ORDER BY HIREDATE ASC LIMIT 5;


/*
	Query 5
*/
SELECT E.ENAME, E.JOB, D.DNAME FROM EMP AS E
JOIN DEPT AS D ON D.DEPTNO = E.DEPTNO
WHERE E.MGR = (SELECT EMPNO FROM EMP WHERE ENAME LIKE 'JONES');
